### ISSUE TITLE
Redirected to error message when grabbing duty

### ISSUE THREAD

**Issue by chrisjwelly** [commit-tech/takoyaki#280]
When trying to grab duties, I get this error: 
![](https://i.imgur.com/b65BnTa.png)
I presume it's the 500 Internal Server Error.

Despite this error message, upon returning to the duty timetable, I still managed to grab the duty. 
For reference if needed: error encountered when using Firefox 65.0.2 on my PC, and also Safari on my iPhone.

**Comment by NicholasCF** [comment]
When I grabbed a duty from 1800-2100 in AS8, I got into the error as well, and ended up only grabbing 2 hours from 1800-2000 (this one might be due to misclick on my side). However, when I grabbed the remaining one hour, there is no issue.

**Comment by chrisjwelly** [comment]
Similar to Nicholas, I grabbed a duty from 0800-1000, got this error and managed to get only the 0800-0900 slot while the 0900-1000 was not grabbed. Upon retrying for the 0900-1000 slot, I managed to successfully grab it. 
It seems like the error is more significant for timeslots which are 30 minutes long rather than timeslots which are 1 hr long
