### ISSUE TITLE
Problem reports do not work when there are non-existent users

### ISSUE THREAD

**Issue by dcshzj** [commit-tech/takoyaki#345]
Currently, the problem reports page does not work as there are some of the reports that are made by old members whose accounts have already been deleted. There should be some exception handling for issues that are reported/tagged to a deleted account.

**Comment by chrisjwelly** [comment]
I added a quick fix in #346 . Re-reported a variant of this issue in #347 with my hope that some day the problem report can show the name of the old members as well.
