### ISSUE TITLE
When emailing dropped duties, only send one email

### ISSUE THREAD

**Issue by donjar** [commit-tech/takoyaki#69]
e.g. when the duties at 10am-11am and 11am-12pm is dropped, currently the system sends two emails, one for each slot. Would be great to merge them into one email

**Comment by donjar** [comment]
Enhancement: do it like e.g. "10am-12pm, 1pm-3pm, 4pm-5pm"

**Comment by indocomsoft** [comment]
Fixed by fab16a3202d1d39f14c5a2505245dd6c1a10a0ec
