### ISSUE TITLE
Some duties are not properly merged in duties#index

### ISSUE THREAD

**Issue by donjar** [commit-tech/takoyaki#70]
See duty.nussucommit.com

**Comment by donjar** [comment]
Possible repro:
1. Get 12pm-2pm slot allocated
2. Your friend passes 11am-12pm duty to you
3. Grab the 11am-12pm duty

**Comment by sreycodes** [comment]
I do not understand this issue.

**Comment by donjar** [comment]
It's a bug in duties#index view. Have you tried to reproduce the issue as I
mentioned?

**Comment by sreycodes** [comment]
I believe my credentials aren't in heroku yet, will check again when we have i can login

**Comment by indocomsoft** [comment]
I believe this might be due to the issue fixed in 0a8438a2c8cb310bec292f0b3f61293b232ee92a

**Comment by indocomsoft** [comment]
Stale issue. Closing
