### ISSUE TITLE
Clicking "Back" on "Update Default Duties" page does not work

### ISSUE THREAD

**Issue by amrut-prabhu** [commit-tech/takoyaki#83]
Steps to recreate bug:
-Log in as Admin and go to home page
-Click "Update Default Duties" button
-Click "Back" button

Expected behaviour:
Goes back to home page

Actual behaviour:
Goes to "Schedule Availability" page

**Comment by indocomsoft** [comment]
I can't reproduce this -- are you sure it's not just some quick navigation on your part? @amrut-prabhu

**Comment by amrut-prabhu** [comment]
Hmm.. here's a screen recording. But, if you cant reproduce it, I guess it'll be pretty hard to fix. So nvm I guess :/
https://drive.google.com/open?id=1RPWQ5x8EfOClPSo2FqY3OfWICioyC4oM

**Comment by indocomsoft** [comment]
OH that. Ok that shld be easily fixable
